server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.245.3:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


  mail:
    host: smtp.163.com
    username: gnomeshgh19lvu@163.com
    password: PDXRJUZTIABQLCRE
    properties:
      from: gnomeshgh19lvu@163.com


  data:
    redis:
      database: 0
      host: 192.168.245.3
      port: 6379
      password: 123456




#  mail:
#    host: smtp.163.com
#    username: gnomeshgh19lvu@163.com
#    password: PDXRJUZTIABQLCRE
#    port: 465
#    properties:
#      from: gnomeshgh19lvu@163.com
#      mail:
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory



